/* eslint-disable no-unused-vars */

import testHtmlElement from './unit/test-html-element.mjs'
import testMDCode from './unit/test-md-code.mjs'
import testMDEscape from './unit/test-md-escape.mjs'
import testMDHeader from './unit/test-md-header.mjs'
import testMDHorizontal from './unit/test-md-horizontal.mjs'
import testMDImage from './unit/test-md-image.mjs'
import testMDLink from './unit/test-md-link.mjs'
import testMDList from './unit/test-md-list.mjs'
import testMDListedNested from './unit/test-md-list-nested.mjs'
import testMDListOrd from './unit/test-md-list-ord.mjs'
import testMDQuote from './unit/test-md-quote.mjs'
import testMDRef from './unit/test-md-ref.mjs'
import testMDText from './unit/test-md-text.mjs'
import testMDVideo from './unit/test-md-video.mjs'
import testModule from './unit/test-module.mjs'
